[package]
name = "tch-train"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tch = "0.6.1"
rand_pcg = "0.3.1"

mnist-data = { path = "../mnist-data" }
