[package]
name = "torch-rust-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tch = "0.6.1"
tract-core = "0.15.8"
tract-onnx = "0.15.8"
