[package]
name = "tract-mnist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tract-onnx = "0.15.8"
rand_pcg = "0.3"

mnist-data = { path = "../mnist-data" }
